### ISSUE TITLE
in the page " plagiarism/moss/settings.php  "  Enable moss cannot be enabled.

### ISSUE THREAD

**Issue by boychunli** [hit-moodle/moodle-plagiarism_moss#2]
Moss Anti-Plagiarism Plugin is developped by Harbin Institute of Technology. The plagiarism engine is Moss. 

Enable moss   

Moss account  

After enable the  "Enable moss" and  set  the "Moss account" , I found that there still "userid=0" in the  moss file.

Moreover, the owner of moss file has been  www-data.

**Comment by sunner** [comment]
The plugin does not modify the moss file. The account is passed to moss by argument. So "userid=0" is ok.

BTW, do not forget to run the cron

**Comment by boychunli** [comment]
但，我enable后，即打对钩，再访问这个网址，还是显示没有那个“对钩”

On Thu, Jul 14, 2011 at 9:34 PM, sunner
reply@reply.github.com
wrote:

**Comment by sunner** [comment]
多谢。昨天做windows的支持引入了这个bug，已修复，试试看
