### ISSUE TITLE
MOSS 

### ISSUE THREAD

**Issue by kanikeabhishek** [hit-moodle/moodle-plagiarism_moss#20]
Can I use Moss as plug-in installation so that through onlinejudge assignment i can run and judge student submitted java files through Moss..... Beacuse the sandbox supports only C/C++ programs judging....
Any help will be appreciated if you can please tell me how to judge java programs through sandbox as well!!!

**Comment by sunner** [comment]
MOSS has nothing related with Online Judge. You must do coding to add java support to sandbox.
