### ISSUE TITLE
反抄袭工作不了

### ISSUE THREAD

**Issue by boychunli** [hit-moodle/moodle-plagiarism_moss#6]
cron 的执行结果，

---Moss begins---
    Found 1 moss instances to measure
    Measure 简单计算累加 (16) in C语言吕春利
    "/var/www/moodle21/plagiarism/moss/moss" -d -u 868134010 -l c /var/moodle21data/temp/moss/4/_/_
    Processing http://moss.stanford.edu/results/944539780
++ cURL request for "http://moss.stanford.edu/results/944539780" failed, HTTP response code: HTTP/1.1 301 Moved Permanently
 ++
- line 1127 of /lib/filelib.php: call to debugging()
- line 235 of /plagiarism/moss/moss.php: call to download_file_content()
- line 163 of /plagiarism/moss/moss.php: call to moss->save_results()
- line 87 of /plagiarism/moss/moss.php: call to moss->call_moss()
- line 331 of /plagiarism/moss/lib.php: call to moss->measure()
- line 145 of /lib/plagiarismlib.php: call to plagiarism_plugin_moss->cron()
- line 131 of /lib/cronlib.php: call to plagiarism_cron()
- line 79 of /admin/cron.php: call to cron_run()
  can not read http://moss.stanford.edu/results/944539780
  ---Moss done---

另外在我的 /var/moodle21data/temp/moss/4/目录下的作业的个数也不对，全体提交作业有30几个，而这个目录下只有3个作业

不知什么原因，请指点：）

**Comment by sunner** [comment]
1. 你的curl相关配置没有让curl自动处理http 301消息。没关系，最新代码里已经兼容此问题了
2. 你没有设文件名通配符，就代表什么文件都不处理，结果就是什么都不会有
3. 只有作业启用了moss以后提交的作业才会被处理

**Comment by boychunli** [comment]
1、我今天更新了最新的代码，不知是否已经兼容这个问题（没有让curl自动处理http 301消息）
1. 通配符我用过\*    _.c   ,
   在/var/moodle21data/temp/moss/下的确有文件，但只是部分文件（只有3个），我想这个/temp/moss文件下的的内容是把文件抽取来另存的吧，但我这个系统中好像没有抽取全，（全部文件（30几个）都是_.c的文件）
   3、作业启用了moss，不然cron不会出现

---Moss begins---
    Found 1 moss instances to measure
    Measure 简单计算累加 (16) in C语言吕春利
    "/var/www/moodle21/plagiarism/moss/moss" -d -u 868134010 -l c
/var/moodle21data/temp/moss/4/_/_.c
    Processing http://moss.stanford.edu/results/489889307
++ cURL request for "http://moss.stanford.edu/results/489889307"
failed, HTTP response code: HTTP/1.1 301 Moved Permanently
 ++
- line 1127 of /lib/filelib.php: call to debugging()
- line 235 of /plagiarism/moss/moss.php: call to download_file_content()
- line 163 of /plagiarism/moss/moss.php: call to moss->save_results()
- line 87 of /plagiarism/moss/moss.php: call to moss->call_moss()
- line 331 of /plagiarism/moss/lib.php: call to moss->measure()
- line 145 of /lib/plagiarismlib.php: call to plagiarism_plugin_moss->cron()
- line 131 of /lib/cronlib.php: call to plagiarism_cron()
- line 79 of /admin/cron.php: call to cron_run()
  can not read http://moss.stanford.edu/results/489889307
  ---Moss done---

2011/9/20 Sun Zhigang
reply@reply.github.com:

**Comment by boychunli** [comment]
补充
系统是ubuntu10.04
moodle 2.1 八月1号的那个

2011/9/20 lv chunli lvchunli@gmail.com:

**Comment by sunner** [comment]
我是看到这个issue之后更新的代码。再重新更新一下吧

通配符应该是有，github把它解释成别的了。这个不是问题

moss肯定启用了，但怀疑你启用完了，已经有学生交过作业才启用的。启用前提交的都不会处理的。不过，如果没打开开发者调试模式的话，moss是会在处理完毕后，将所有中间文件都清理了的。所以你看到的未必是全貌。

刚才又更新了一下代码，输出了上传的文件数。你再试试

**Comment by sunner** [comment]
另外，最好把moodle升级到上个星期发布的稳定版。那一版用了我的一个patch，解决了删除作业后，对应的moss相关数据不被删除的bug

**Comment by sunner** [comment]
问题解决了吗？可以close this issue了吗？

**Comment by boychunli** [comment]
非常感谢你，祝你升职：）

根据你的指点，我这几天做了升级moodle，升级moss

但我得到的结果如如下，

---Moss begins---
    Found 2 moss instances to measure
    Measure 简单计算累加(9月26日截止) (16) in C语言吕春利
    "/var/www/moodle21/plagiarism/moss/moss" -d -u 868134010 -l c
/var/moodle21data/temp/moss/4/_/_.c
21 files are uploaded.
    Processing http://moss.stanford.edu/results/442792292/
    can not parse http://moss.stanford.edu/results/442792292/
    Measure     计算累加和2  (9月26日截止) (17) in C语言吕春利
    "/var/www/moodle21/plagiarism/moss/moss" -d -u 868134010 -l c
/var/moodle21data/temp/moss/5/_/_
27 files are uploaded.
    Processing http://moss.stanford.edu/results/163883184/
    Got 35 pairs
---Moss done---

如下这个是正确结果
Measure     计算累加和2  (9月26日截止) (17) in C语言吕春利
    "/var/www/moodle21/plagiarism/moss/moss" -d -u 868134010 -l c
/var/moodle21data/temp/moss/5/_/_
27 files are uploaded.
    Processing http://moss.stanford.edu/results/163883184/
    Got 35 pairs

但也有得到如下结果的
21 files are uploaded.
    Processing http://moss.stanford.edu/results/442792292/
    can not parse http://moss.stanford.edu/results/442792292/

这个结果，我还没有仔细分析，也许真没有抄袭：）
但界面上还是显示未判别状态

2011/9/29 Sun Zhigang
reply@reply.github.com:

**Comment by sunner** [comment]
访问那个页面可以知道，确实是没有抄袭检测出来。不过程序输出信息不明确，现在改了，麻烦再更新一下，谢谢
